### ISSUE TITLE
Any solution to connect from localhost?

### ISSUE THREAD

**Issue by richellyitalo** [SociallyDev/Spaces-API#11]
Any solution to connect from localhost?

**Comment by SociallyDev** [comment]
@richellyitalo You can connect to a local S3 API by providing the appropriate host like:
<br />

```php
$space = new SpacesConnect($key, $secret, $space_name, $region, $host = "localhost");
```

If you meant connecting to Spaces from a local computer (Instead of a server), this wrapper shouldn't have any problem with that. 
<br />
If this isn't the problem you're facing, can you please elaborate?
Thanks!

**Comment by richellyitalo** [comment]
I was trying send file from localhost by Wampserver, but show me the error about not certificate (code 60):
** AWS HTTP error: cURL error 6: Could not resolve host: ----.nyc3.localhost (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)**

Only works after defined on php.ini the certified bellow.

[https://curl.haxx.se/ca/cacert.pem]https://curl.haxx.se/ca/cacert.pem

curl.cainfo = "path_to_cert\cacert.pem"

With host='localhost' doesnt works, only after set curl.cainfo on php.ini.

**Comment by SociallyDev** [comment]
@richellyitalo Any secure wrapper/SDK will only send data through a secure encrypted connection (https), it seems like ----.nyc3.localhost does not send a valid SSL certificate.
<br />
The solution you've found should work for localhost testing, interfacing with the real S3 API shouldn't throw this problem. If you'd like to test your code without editing certificates, you can use a proxy such as [ngrok](https://ngrok.com) on top of your localhost S3 API.

**Comment by richellyitalo** [comment]
Nice tip. 
Thanks @SociallyDev
