### ISSUE TITLE
upload inside folder

### ISSUE THREAD

**Issue by saudkhan306** [SociallyDev/Spaces-API#17]
Hi,
Thanks for the great contribution!

I have an issue related to uploading in folder. I have created a directory **UPLOADS**, but when I use function
`$space->UploadFile('uploads/image.png', "private", 'my_file_name.png', 'image/png');`

that function does not upload file in folder "**UPLOADS**", rather get uploaded in main root directory.

Kindly help me out with this.

**Comment by SociallyDev** [comment]
Hello,
To upload to a folder in Spaces, you should add that folder to the upload path like this:
```php
$space->UploadFile('uploads/image.png', "private", 'uploads/my_file_name.png', 'image/png');
```

**Comment by saudkhan306** [comment]
Thank you so much!
