### ISSUE TITLE
listing for folder

### ISSUE THREAD

**Issue by schmidtl4** [SociallyDev/Spaces-API#18]
Is it possible with this package to get a listing of a particular folder vs. all objects in the Space?

**Comment by schmidtl4** [comment]
Not in README.md but through trial and error the answer is "yes", as follows: 
`$files = $space->ListObjects("targetDirectory/")`
where targetDirectory is in the root of your space.  The trailing slash is essential otherwise, the search is looking for a file with the name "targetDirectory".
Also note that this can be extended to "targetDirectory/subDirectory/" etc.

**Comment by SociallyDev** [comment]
Hello, sorry for the late response.
Yes, that is the correct method.

It isn't documented because the S3 standard doesn't have folders, they're just URI paths.
[Here's their explanation](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/using-folders.html).

> Amazon S3 has a flat structure with no hierarchy like you would see in a file system. However, for the sake of organizational simplicity, the Amazon S3 console supports the folder concept as a means of grouping objects. Amazon S3 does this by using a shared name prefix for objects (that is, objects that have names that begin with a common string). Object names are also referred to as key names.
