### ISSUE TITLE
Multi-part uploads

### ISSUE THREAD

**Issue by schmidtl4** [SociallyDev/Spaces-API#21]
Any plans to support multi-part uploads?  Apparently this is recommended for any file size > 500MB.

Thanks.

**Comment by SociallyDev** [comment]
I'll add this feature in the next major release.

**Comment by CodeJunkieio** [comment]
When do we think that might be? I'm interested in using this but the lack of multi-part upload support is kind of a buzz kill

**Comment by 6vl** [comment]
Help me upload to 1 folder 
or move to 1 1 folder 
thanks

**Comment by schmidtl4** [comment]
Any update on the planned timing for a multi-part upload feature? Much appreciated.

**Comment by CodeJunkieio** [comment]
@schmidtl4 There doesn't seem to be much support anymore, I'll fork it and let you know once I have something working

**Comment by schmidtl4** [comment]
@CodeJunkieio - were you able to get something working?

**Comment by SociallyDev** [comment]
Hey guys, it's been a couple of years. I hope you guys are doing well. Spaces-API now supports multipart uploads natively. Just upload a file as always, and it'll automatically slice & stream to optimize the uploads!

```php
$my_space = Spaces("ACCESS KEY", "SECRET KEY")->space("my_space", "nyc3");

//Upload a local stored file.
$my_space->uploadFile("path/to/my/file.txt", "path/on/space.txt", "private");
```

Read the new README for more info: https://github.com/SociallyDev/Spaces-API
