### ISSUE TITLE
Ability to upload directory as public

### ISSUE THREAD

**Issue by tonybahama** [SociallyDev/Spaces-API#22]
hi!

We did not manage to upload a full directory and set all files to public in it in one run.

All uploaded files are private, and then we have to iterate and set them to public one by one. We have 1 million files, it takes 4-5 minutes per folder, we have 6-9000 folders.

Any idea? The S3 lib should be capable of doing this.

**Comment by SociallyDev** [comment]
Hey, can you share the code you wrote for this?

**Comment by tonybahama** [comment]
We did not manage to upload them yet. I just know it is possible with the amazon s3 SDK but your API does not pass this argument.

That is why I asked if you knew anything. We tried several times but had no luck so far.

**Comment by SociallyDev** [comment]
Sorry for the delay.
It's possible to add a directory at once with public files.
This is an edge case though, so I'll just write the function for you.

First, create a space as normal, then:

```php
$directory = "My directory's location";
$uploadLocation = "myFiles";
$privacy = "public-read";


$space->client->uploadDirectory($directory, $space->space, $uploadLocation, ["params" => ["ACL" => $privacy]]);
```

**Comment by tonybahama** [comment]
Have you tested this code?

**Comment by SociallyDev** [comment]
Hey, sorry, I wrote it for an older AWS S3 SDK version.
I've edited my previous comment with code that should work with the latest SDK.

Please try it out and let me know.

**Comment by tonybahama** [comment]
It worked! Thank you!
It saved 4 minutes per product for us, 6000 products...

I recommend you put this into the source code as an option for others!
