### ISSUE TITLE
 $space->client is empty {}

### ISSUE THREAD

**Issue by softenggkumar** [SociallyDev/Spaces-API#23]
Hello,

I am new to DigitalOcean Space API integration, for some reason I am getting following error while accessing ListObjects() method.

**Code**
`$space = new SpacesConnect($accessKey, $secretKey, $spaceName, $region);
 $spaceList = $space->ListObjects();`

**Error Message**
`"message": "{\"error\":{\"message\":null,\"code\":null,\"type\":null,\"http_code\":null}}"
 "line": 506`

Note: $space->client is empty {}

Question : Is there any settings that I need to enable in Digital Ocean Space

**Comment by SociallyDev** [comment]
Hey, looks like there's a problem with the region, can you check it?

**Comment by softenggkumar** [comment]
I checked the regions, it is nyc3. Not sure for some reason I am getting the above mentioned error only when I am trying to upload file from my local environment but in server the same code I can able to upload the files without any issues.

Any suggestion to make is work in my local environment ?

**Comment by SociallyDev** [comment]
Hm, I've so far been unable to reproduce this error.
Maybe it's a network issue, does your local environment have access to the internet?

Otherwise, can you try directly using AWS-SDK to figure out if the error is with this wrapper?
Just try this code:

```php
require_once(dirname(__FILE__)."/aws/autoloader.php"); //From Spaces-API.


$accessKey = "";
$secretKey = "";
$spaceName = "";
$region = "nyc3";


$aws = Aws\S3\S3Client::factory(array(
            'region' => $region,
            'version' => 'latest',
            'endpoint' => "https://".$spaceName.".".$region.".digitaloceanspaces.com",
            'credentials' => array(
                      'key'    => $accessKey,
                      'secret' => $secretKey,
                  ),
            'bucket_endpoint' => true,
            'signature_version' => 'v4-unsigned-body'
          ));


$objectsX = $aws->getIterator("ListObjects", array("Bucket" => $spaceName));
$objects = [];
foreach ($objectsX as $object) { $objects[] = $object; }

print_r($objects);
```
