### ISSUE TITLE
Upload directly without main path

### ISSUE THREAD

**Issue by kareemzok** [SociallyDev/Spaces-API#24]
Hello, i m ondering is it possible to upload image using base64_6ecode function instead of having a path??
Such as the following:

```
$first_path = "../img-pbc/b/1/" . $firstImg;
 file_put_contents($first_path, base64_decode($Data['firstImageBitmap']));
```

**Comment by SociallyDev** [comment]
Hey,
It should be possible already. Here's an example:

```php
$content = "My text";
$saveAs = "test.txt";
$access = "public";

$space->UploadFile($content, $access, $saveAs);
```

**Comment by kareemzok** [comment]
> Hey,
> It should be possible already. Here's an example:
> 
> ```
> $content = "My text"; //You can use a decode function here too.
> $saveAs = "test.txt";
> $access = "public";
> 
> $space->UploadFile($content, $access, $saveAs);
> ```

Thank @SociallyDev  for your reply but what about the case of the image? we ca  pass the image in $content ?  then save it in the space of digital ocean?

**Comment by SociallyDev** [comment]
Yes, that should work. You should also set the mime type like this:

```php
$content = "My text"; //You can use a decode function here too.
$saveAs = "test.txt";
$access = "public";
$mime = "image/png";

$space->UploadFile($content, $access, $saveAs, $mime);
```

Let me know if you face a problem!

**Comment by kareemzok** [comment]
Thanks, It works !!
