### ISSUE TITLE
Unable to delete folder

### ISSUE THREAD

**Issue by warely** [SociallyDev/Spaces-API#25]
I’m running the ‘$space->DeleteObject($file_name);’ command to delete a folder (per documentation), and get a successful response, but the folder does not delete in the digitalocean spaces explorer GUI.

**Comment by SociallyDev** [comment]
As far as I understand, folders don't really exist in the S3 standard, they're just prefixes to filenames.

A folder should disappear as long as all files that have it in its path are deleted.
