### ISSUE TITLE
Why uploads doesn't work when using absolute path?

### ISSUE THREAD

**Issue by Dibbyo456** [SociallyDev/Spaces-API#28]
Hello,
I'm facing a issue. If I use this uploads works fine. ✌

```php
$path_to_file = "image.png";
$space->UploadFile($path_to_file, "public");
```

But if I use this

```php
$path_to_file = realpath("image.png");
```
or this

```php
$path_to_file = __DIR__ . "/image.png";
```

Then I get error like this:

```Fatal error: Uncaught SpacesAPIException: {"error":{"message":null,"code":"SignatureDoesNotMatch","type":"client","http_code":403}} in C:\wamp64\www\script\inc\vendor\sociallydev\spaces-api\spaces.php:506 Stack trace: #0 C:\wamp64\www\script\inc\vendor\sociallydev\spaces-api\spaces.php(286): SpacesConnect->HandleAWSException(Object(Aws\S3\Exception\S3Exception)) #1 C:\wamp64\www\script\test1.php(18): SpacesConnect->UploadFile('C:\\wamp64\\www\\t...', 'public-read') #2 {main} thrown in C:\wamp64\www\script\inc\vendor\sociallydev\spaces-api\spaces.php on line 506```

PHP 7.3.4
Windows 10
WAMP Server

**Comment by SociallyDev** [comment]
I can't reproduce this error, can you check if [this line](https://github.com/SociallyDev/Spaces-API/blob/ad0726e41e7a3a10c367917421c7b327256a358e/spaces.php#L271) actually reads your file?
