### ISSUE TITLE
No AWS class loaded

### ISSUE THREAD

**Issue by GraninV** [SociallyDev/Spaces-API#3]
Hi.
I am getting "No AWS class loaded". What could be a reason for that...? Thank you.

**Comment by SociallyDev** [comment]
Hello!
That error occurs when an already installed AWS API SDK isn't available and the AWS SDK that comes pre-bundled with this wrapper isn't available either.
You should download the AWS folder as well if you're using a manual install (and check that the $non_composer_aws_lib var has the correct path set) or in case you're using composer it should download the SDK automatically but in case it didn't, just recompile the project.
