### ISSUE TITLE
Setting metadata

### ISSUE THREAD

**Issue by schmidtl4** [SociallyDev/Spaces-API#30]
Is there a way to set the metadata for a file?

**Comment by SociallyDev** [comment]
Hello, there's no such way directly, you can call the underlying AWS client that does have that feature directly though, something like this:

```php
$space->client->putObject(array(
    'Bucket' => $space->space,
    'Key' => $save_as,
    'Body' => $file,
    'ACL' => $access,
    'ContentType' => $mime_type
))
```

**Comment by schmidtl4** [comment]
Thanks for the reply.  I only want to set the content-type metadata for files I'm uploading.  How would I use the code above?  Would I use it instead of the $space->UploadFile or call this after the file is already uploaded.

**Comment by UFO-84** [comment]
Hi,

`
                $spaces = Spaces($targetAccount['accessKey'], $targetAccount['secretKey']);
                $storage = $spaces->space($targetAccount['space']['spaceName'], $targetAccount['space']['regionName']);
                $output = $storage->uploadFile($srcFullFilePath, $destinationPath, $privacy);

This works fine. Can you introduce something so we can add metadata while uploading, please?
`

The example you posted above causing error: "Undefined property: Space::$client"

Can you do something on it, or do you want me to create another issue?

**Comment by UFO-84** [comment]
Well, I edited your class, and this works fine, I am posting the method here, if anyone needed ...


    /*
    Uploads a file.
    @$metadata array :Example: $metaData = ['width' => '10','height' => '10'];
    */
    function uploadFile($filePath, $saveAs = "", $privacy = "private", $metaData = [])
    {
        if (empty($saveAs))
        {
            $saveAs = $filePath;
        }
        if ($privacy == "public")
        {
            $privacy = "public-read";
        }

        $newMetaData = [];
        if(!empty($metaData))
        {
            foreach ($metaData as $metaKey => $metaValue)
            {
                $newMetaData['x-amz-meta-'.$metaKey] = $metaValue;
            }
        }

        $metaData = [
            "params" => [
                'Metadata' => $newMetaData
            ]
        ];

        $content = fopen($filePath, "r");
        $result = $this->s3->upload($this->name, $saveAs, $content, $privacy, $metaData);

        fclose($content);
        return SpacesResult($result);
    }

**Comment by SillyPhp** [comment]
hey could you help me regarding this @SociallyDev i am not able to set Content-Disposition meta tags while uploading file however i use the way @UFO-84 provided but the issue is it set the meta as custom key as "x-amz-meta-<Content-Disposition>" bu it want to set "Content-Disposition" with some value as it is, not as custom key like x-amz etc help about it

**Comment by ashikhassan** [comment]
Dear @SociallyDev

Unable to set 'ContentType' => $mime_type

`
require_once("vendor/autoload.php");
if (!defined('spaceAccessKey')) define('spaceAccessKey', '');
if (!defined('spaceSecretKey')) define('spaceSecretKey', '');
if (!defined('spaceName')) define('spaceName', '');
if (!defined('spaceEndpoint')) define('spaceEndpoint', 'fra1');

$my_space = Spaces(spaceAccessKey, spaceSecretKey)->space(spaceName, spaceEndpoint);
$my_space->privacy("public");

$metaData=['Content-Type' => $_FILES["file"]["type"]];
$my_space->uploadFile($_FILES["file"]["tmp_name"],"test/".$_FILES["file"]["name"],'public',$metaData);

`

**Comment by dashpilot** [comment]
@ashikhassan  ContentType is not part of the metadata, but it is part of the "params" array. This is how I solved it:

```
function uploadFile($filePath, $saveAs = "", $privacy = "private", $mime) {
    if(empty($saveAs)) { $saveAs = $filePath; }
    if($privacy == "public") { $privacy = "public-read"; }

    $content = fopen($filePath, "r");
    $result = $this->s3->upload($this->name, $saveAs, $content, $privacy, array('params' => array('ContentType' => $mime)));

    fclose($content);
    return SpacesResult($result);
  }
```
example usage:

```
$mime = 'application/json';
uploadFile($filePath, $saveAs, $privacy, $mime);
```
Hope that helps!
