### ISSUE TITLE
ListObjects

### ISSUE THREAD

**Issue by consigliere23** [SociallyDev/Spaces-API#33]
Why this is not working? 
It just wont list folder content? 
Anyone has this issue?

**Comment by CodeJunkieio** [comment]
@consigliere23 I haven't had any issues... Perhaps this is a misunderstanding.
DigitalOcean Spaces were made to be S3 compatible, S3 doesn't have folders, so even though you see folders in the DO admin panel what that actually is, is a prefix on objects. So you should get a large list of objects and those who are in "folders" should actually just have prefix of the "folder" name

Hope that helps, If you understand what I'm saying and it doesn't answer your question, try posting some code and a screenshot of your space so we can better help you

**Comment by SociallyDev** [comment]
Hey @consigliere23, it's been a while. In case you still want to know how to list all files within a folder, here's how you do it:

```php
$my_space = Spaces("ACCESS KEY", "SECRET KEY")->space("my_space", "nyc3");

//Lists all files in a folder inside your Space.
$my_space->listFiles("my-folder");
```

@CodeJunkieio thanks for helping with so many issues man!
