### ISSUE TITLE
GIF upload Issue

### ISSUE THREAD

**Issue by adapana** [SociallyDev/Spaces-API#36]
I uploaded GIF file, file upload successfully done.
But when I download the file from space, it was not GIF. That file becomes static JPEG file.

The file extension was .gif but the animation was gone.

If you have any solution then please share.

**Comment by SociallyDev** [comment]
Hey, I just tried this with the new Spaces-API & it seems that gifs are indeed downloaded as gifs. It could've been a problem with the old version, but it does seem to be working as intended now!
