### ISSUE TITLE
Upload image from external url?

### ISSUE THREAD

**Issue by tcagkansokmen** [SociallyDev/Spaces-API#37]
Is that possible?

I tried to take image from url

```
  $path_to_file = "https://blabla.com/450x0/images/extra/thumb/blabla.jpg";
  $path_info = pathinfo($path_to_file);

  $newpath = "images/product/450x0/".$newname;
  $space->UploadFile($path_to_file, "public", $newpath);
```

Bu it send 73bytes of empty file.
How can we make it?

**Comment by ridvanaltun** [comment]
İt is not possible.

https://stackoverflow.com/questions/7586533/is-it-possible-to-upload-to-s3-directly-from-url-using-post

**Comment by Andrej64** [comment]
It is possible.
$file = file_get_contents($url);
$space->UploadFile($file, "public", $newpath);

**Comment by SociallyDev** [comment]
Hey @tcagkansokmen, sorry for the (Super) late reply. It's not possible to directly upload a file to either S3 or Spaces from a URL. You can, however, download the contents of the image from a URL, and then use Spaces-API to upload that to your Space!
