### ISSUE TITLE
whatever file i'm upload on DO, it is having errors!

### ISSUE THREAD

**Issue by avinashseth** [SociallyDev/Spaces-API#39]
Hi, i'm trying to upload files on DO using this package and everytime, I see file uploaded has error

my code 

`
$key = "key";

$secret = "secret";

$space_name = "name";

$region = "region";

$space = new SpacesConnect($key, $secret, $space_name, $region);

$space->UploadFile("my/local/file/path/filename.png", "public", "do_folder/filename.png",$file->getClientMimeType());

`

**Comment by SociallyDev** [comment]
Hello, Spaces-API recently went through a rewrite & I've made an attempt at squashing all bugs. This should work for you now. Here's how the new upload method works:

```php
$my_space = Spaces("ACCESS KEY", "SECRET KEY")->space("my_space", "nyc3");

//Upload some text.
$my_space->upload("Super cool content", "example.txt");
```

Also, I'm really sorry I couldn't reply to you faster.
