### ISSUE TITLE
Bucket's Lifecycle Rules?

### ISSUE THREAD

**Issue by hsleewis** [SociallyDev/Spaces-API#4]
Are you planning to add Bucket's Lifecycle Rules?

More info here: https://developers.digitalocean.com/documentation/spaces/#get-bucket-lifecycle

**Comment by jgannondo** [comment]
@hsleewis We do allow you to add lifecycle delete rules. Are you looking for something different? Please let me know.

**Comment by nickjanus** [comment]
@jgannondo I think @hsleewis is referring to support for lifecycle rules in this api wrapper.
