### ISSUE TITLE
SpacesAPIException

### ISSUE THREAD

**Issue by ajisu143** [SociallyDev/Spaces-API#40]
Hi,

I am getting error "Fatal error: Uncaught exception 'SpacesAPIException' with message '{"error":{"message":null,"code":null,"type":null,"http_code":null}}'.Please suggest necessary steps to fix this issue.

**Comment by edibudimilic** [comment]
I'm having the same problem. Exception is not getting a proper message. Issue is with cURL and my guess it's SSL validation since Space without a CDN doesn't have SSL certificate setup.

**Comment by ajisu143** [comment]
This api does not work with new version.i fixed this issue by downloading aws s3 sdk from aws site. check this link "https://help.dreamhost.com/hc/en-us/articles/115002875812-Sample-AWS-PHP-v3-SDK-code".it will help you.

**Comment by edibudimilic** [comment]
I fixed it manually by editing:
> vendor\sociallydev\spaces-api\aws\GuzzleHttp\Handler\CurlFactory.php

I changed `CURLOPT_SSL_VERIFYHOST` and `CURLOPT_SSL_VERIFYPEER` both to `FALSE` and it works without any exceptions.

**Comment by johncoles** [comment]
Yup had to do this too.

**Comment by SociallyDev** [comment]
Hello, Spaces-API v2 is a complete rewrite that defaults AWS's error management. This error should no longer happen.
You can read the new README here: https://github.com/SociallyDev/Spaces-API
