### ISSUE TITLE
how to upload image from ionic upload to digital occean

### ISSUE THREAD

**Issue by dragonheart90** [SociallyDev/Spaces-API#41]
i am trying to upload image but its not uploading instead it just takes path of image but not blob image is stored in space

**Comment by SociallyDev** [comment]
Hey, Spaces-API recently went through a rewrite & now it should be easier than ever to upload a file!
Here's an example:
```php
$my_space = Spaces("ACCESS KEY", "SECRET KEY")->space("my_space", "nyc3");

//Upload a local stored file.
$my_space->uploadFile("path/to/my/file.txt", "path/on/space.txt", "private");
```

You can read the README for more info: https://github.com/SociallyDev/Spaces-API
