### ISSUE TITLE
URGENT: Composer install not working

### ISSUE THREAD

**Issue by schmidtl4** [SociallyDev/Spaces-API#42]
I consistently get this error when doing a composer require or install:
Update failed (Failed to execute git status --porcelain --untracked-files=no
fatal: unknown index entry format 0x74650000

After replying "yes" to the composer question about reinstalling instead I get:
[RuntimeException]
{and same error as above}

What can be done to get this back up and running
![image](https://user-images.githubusercontent.com/1418698/82097210-4e983180-96b7-11ea-8347-c24fd492081c.png)

**Comment by schmidtl4** [comment]
It may be that this has a conflict with another package.  If I use composer and sociallydev/spaces-api is the only thing in the composer.json file, then everything installs fine.  In the scenario above, the spaces-api package was second to last and consistently would not install.  Are there any packages with which there is a known conflict?  Perhaps aws/aws-sdk-php?

**Comment by SociallyDev** [comment]
Hey, Spaces-API just went through a major rewrite & this should be working for you now!
Here's how to install Spaces-API v2 via Composer: https://github.com/SociallyDev/Spaces-API#b-the-composer-method.

Also, I'm really sorry I couldn't reply to you sooner. I hope you were able to solve this problem on your own as well!
