### ISSUE TITLE
Error while download file.

### ISSUE THREAD

**Issue by ganeshnadar17** [SociallyDev/Spaces-API#44]
Hello,

Fatal error while downloading file server 

$download_file = $path[$data['action']];
$save_as = substr($download_file, strrpos($download_file, '/') + 1);
$space_data = $space->DownloadFile($download_file, $save_as);

<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Aws\Handler\GuzzleV5\GuzzleHandler::Aws\Handler\GuzzleV5\{closure}() must be an instance of Exception, string given, called in htdocs/system/helper/pd/aws/GuzzleHttp/Promise/Promise.php on line 203

Could someone help me, please?

Thank you!

**Comment by SociallyDev** [comment]
Hey, sorry for the (Super) late reply. I've been writing the v2. File downloads should be working for you now:
```php
$my_space = Spaces("ACCESS KEY", "SECRET KEY")->space("my_space", "nyc3");

//Saves the file content to the local path, and returns file info.
$info = $my_space->downloadFile("my-file.txt", "save-path/file.txt");
```

Check out the new README: https://github.com/SociallyDev/Spaces-API
