### ISSUE TITLE
Problem function Creating Temporary Links

### ISSUE THREAD

**Issue by juanrdlo** [SociallyDev/Spaces-API#46]
hello community,
I have tried to use this function, but it sends me the following error. i have php 7.4

`A PHP Error was encountered
Severity: Notice

Message: Trying to access array offset on value of type null

Filename: Aws/RetryMiddleware.php

Line Number: 75

Backtrace:

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/aws/Aws/RetryMiddleware.php
Line: 75
Function: _error_handler

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/aws/Aws/S3/S3Client.php
Line: 501
Function: Aws\{closure}

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/aws/Aws/RetryMiddleware.php
Line: 141
Function: Aws\S3\{closure}

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/aws/GuzzleHttp/Promise/Promise.php
Line: 203
Function: Aws\{closure}

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/aws/GuzzleHttp/Promise/Promise.php
Line: 156
Function: callHandler

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/aws/GuzzleHttp/Promise/TaskQueue.php
Line: 47
Function: GuzzleHttp\Promise\{closure}

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/aws/GuzzleHttp/Promise/Promise.php
Line: 246
Function: run

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/aws/GuzzleHttp/Promise/Promise.php
Line: 223
Function: invokeWaitFn

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/aws/GuzzleHttp/Promise/Promise.php
Line: 267
Function: waitIfPending

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/aws/GuzzleHttp/Promise/Promise.php
Line: 225
Function: invokeWaitList

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/aws/GuzzleHttp/Promise/Promise.php
Line: 62
Function: waitIfPending

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/aws/Aws/functions.php
Line: 298
Function: wait

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/aws/Aws/S3/S3Client.php
Line: 334
Function: Aws\serialize

File: /usr/share/nginx/html/proyectos/api_prestamos/vendor/sociallydev/spaces-api/spaces.php
Line: 447
Function: createPresignedRequest

File: /usr/share/nginx/html/proyectos/api_prestamos/application/libraries/SpaceDO.php
Line: 50
Function: CreateTemporaryURL

File: /usr/share/nginx/html/proyectos/api_prestamos/application/controllers/Welcome.php
Line: 25
Function: link_temporal

File: /usr/share/nginx/html/proyectos/api_prestamos/index.php
Line: 315
Function: require_once`

I have verified, and all the settings are right, I am working with DigitalOcean Space.

**Comment by SociallyDev** [comment]
Hey, looks like this wrapper is showing its age when working with AWS'. Give me a day to update this & get back to you.

**Comment by juanrdlo** [comment]
Thank... I'll be waiting, greetings

**Comment by SociallyDev** [comment]
Please try the new v2. It's a complete rewrite.
Here's the code that should work for you:
```php
$my_space = Spaces("ACCESS KEY", "SECRET KEY")->space("my_space", "nyc3");

//Returns a URL that'll work for 15 minutes for this file.
$my_space->signedURL("my-file.txt", "15 minutes");
```

Check out the new README: https://github.com/SociallyDev/Spaces-API
