### ISSUE TITLE
 unexpected 'list' (T_LIST), expecting identifier (T_STRING)

### ISSUE THREAD

**Issue by AndrewTemchishen** [SociallyDev/Spaces-API#47]
PHP Parse error:  syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in /.../vendor/sociallydev/spaces-api/spaces.php on line 52

**Comment by SociallyDev** [comment]
Hello, you should check your copy. I've tested pulling from Composer & using Spaces-API on my own machine and that works fine. I've also tested the code in spaces.php for syntax & it seems to be correct.

**Comment by AndrewTemchishen** [comment]
For which version of php you tested it? Try on 5.6

**Comment by SociallyDev** [comment]
Looked around a bit. Looks like old PHP version didn't allow naming a method in a class as list, so I've changed the name & now it's passing on PHP 5.6!
