### ISSUE TITLE
Use releases for better composer experience

### ISSUE THREAD

**Issue by AndrewTemchishen** [SociallyDev/Spaces-API#48]
When you change a project, make releases so people can switch between them in composer.
Cause last v2 release can break services which use that lib.

**Comment by SociallyDev** [comment]
Hey, thanks for the suggestion! I've added releases.
Now the old Spaces-API can be installed via:
`composer require sociallydev/spaces-api:v1`

And the new one can be installed via:
`composer require sociallydev/spaces-api:v2`

**Comment by AndrewTemchishen** [comment]
Thank you

**Comment by avtomaha** [comment]
@SociallyDev Thanks a lot for new version
