### ISSUE TITLE
Features missing or not working

### ISSUE THREAD

**Issue by adadgio** [SociallyDev/Spaces-API#50]
Hi there, I noticied that this did not work: $this->space->privacy("public")

As well, it's not possible to set a public flag on uploadDirectory (and its not possible to set a whole directory public as well)...

I don't think this library is usable without those, but otherwise, i would be great!

**Comment by SociallyDev** [comment]
Hey,
The correct syntax is:
```php
$spaces = Spaces("ACCESS KEY", "SECRET KEY");
$mySpace = $spaces->space("my-space", "nyc3");

$mySpace->privacy("public");
```


A thing to note: By S3's design, changing a Space's privacy will only make it display an XML list of already public objects. Even if a Space is made public, it never affects the objects which are set to be private, they will remain being private till explicitly made public.

As for uploadDirectory, you might notice it is the same as AWS S3's uploadDirectory, you can even call it directly like:
```php
$mySpace->s3->uploadDirectory(); //Directly calling AWS's method.
```
You can see in [AWS's docs](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3ClientInterface.html#_uploadDirectory) that there isn't an option for object ACLs in uploadDirectory unfortunately.

As for not being able to make a directory public, directories technically don't exist in the S3 design, only object paths do, but you can make all the files inside a directory public like this:
```php
foreach ($mySpace->listFiles("my-folder") as $file) {
  $mySpace->filePrivacy($file["Key"], "public");
}
```

I hope I was of some help at least.
-Devang
