### ISSUE TITLE
I can't figure how to upload an image

### ISSUE THREAD

**Issue by Chamberlainfrancis** [SociallyDev/Spaces-API#52]
I can't figure out how to upload an image using this Spaces-API, I have tried everything I could and  its not working.  After a successful upload, its always showing **Content-Type** as **“application/octet-stream”** in space.

Below is 2 instances - I have tried uploading like so 

`$file = $_FILES['file']['tmp_name'][$i];`
`$bucket->uploadFile($file, $object_name);`

but Content-Type is “application/octet-stream” in space 
but on the other hand when I try testing like so.

`$file = getcwd() . "/images/logo.png";`
`$bucket->uploadFile($file, $object_name);`

it upload successfully as **Content-Type** is **“image/jpeg”** which is how I expect the first example to be like
Please I need help or a better documentation on what to do in this situation

**Comment by avtomaha** [comment]
See [Setting metadata](https://github.com/SociallyDev/Spaces-API/issues/30) issue.
