### ISSUE TITLE
Setting meta tags as main tags not custom tags

### ISSUE THREAD

**Issue by SillyPhp** [SociallyDev/Spaces-API#54]
hey could you help me regarding this @SociallyDev i am not able to set Content-Disposition meta tags while uploading file however i use the way @UFO-84 provided in other thread but the issue is it set the meta as custom key as "x-amz-meta-" bu it want to set "Content-Disposition" with some value as it is, not as custom key like x-amz etc help about it

**Comment by UFO-84** [comment]
I don't think you can custom headers without x-amz-* except they provided. I even asked DO's community to add "Expires" header. It didn't work either.

**Comment by hichamtaoufikallah** [comment]
@SillyPhp If you still looking on how to make it works then here is how:
```
function uploadFile($filePath, $saveAs = "", $privacy = "private", $contentDisposition = 'attachment') {
        if(empty($saveAs)) { $saveAs = $filePath; }
        if($privacy == "public") { $privacy = "public-read"; }

        $content = fopen($filePath, "r");
        $result = $this->s3->putObject(array(
            'Bucket' => $this->name,
            'Key' => $saveAs,
            'Body' => $content,
            'ACL' => $privacy,
            'ContentDisposition' => $contentDisposition
        ));


        fclose($content);
        return SpacesResult($result);
}
```
the [hint](https://github.com/SociallyDev/Spaces-API/issues/30#issuecomment-498835995) from @SociallyDev was enough :)

**Comment by SociallyDev** [comment]
Thanks for your help @hichamtaoufikallah!
