### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by Agimovel** [SociallyDev/Spaces-API#6]
Hello there. I'm openning this issue, but with already a solution that might help others.

When trying to connect to your space with:
`new SpacesConnect($key, $secret, $space_name, $region);`

It might return this error:

> "SignatureDoesNotMatch" 403

Just erase your space_name and will connect. Don't know why it throws this error but this solves the situation.

**Comment by Agimovel** [comment]
Still having this issue when trying to upload a file:
`$space->UploadFile($path, $destination);`

> Message: {"error":{"message":null,"code":"SignatureDoesNotMatch","type":"client","http_code":403}}

**Comment by SociallyDev** [comment]
Hello,
This issue occurs when you add a forward slash to the start of a path, it's an issue of the AWS SDK itself. I'll try to add a filter in the next update.

**Comment by Agimovel** [comment]
My bad, thanks for your contribution.
