### ISSUE TITLE
Fatal error: on line 195

### ISSUE THREAD

**Issue by wildshark** [SociallyDev/Spaces-API#60]
I get an error when I try it on a xampp running on a local PC

Fatal error: Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "ListObjects" on "https://drive7.fra1.digitaloceanspaces.com/?encoding-type=url"; AWS HTTP error: Client error: `GET https://drive7.fra1.digitaloceanspaces.com/?encoding-type=url` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8"?><Error><Code>RequestTimeTooSkewed</Code><RequestId>tx00000000000003d452b28-00602ba (truncated...) RequestTimeTooSkewed (client): - <?xml version="1.0" encoding="UTF-8"?><Error><Code>RequestTimeTooSkewed</Code><RequestId>tx00000000000003d452b28-00602bafa1-2e1d3b4-fra1b</RequestId><HostId>2e1d3b4-fra1b-fra1-zg02</HostId></Error>' GuzzleHttp\Exception\ClientException: Client error: `GET https://drive7.fra1.digitaloceanspaces.com/?encoding-type=url` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8"?><Error><Code>RequestTimeTooSkewed</Code><RequestId>tx00000000000003d452b28-00602ba (truncated...) in C:\xampp\htdocs\bank_io\Spaces-API-master\aws\GuzzleH in C:\xampp\htdocs\bank_io\Spaces-API-master\aws\Aws\WrappedHttpHandler.php on line 195

**Comment by MacroMan** [comment]
I have been unable to replicate this issue, so I am closing this issue. Please raise another should you continue to have problems.
