### ISSUE TITLE
Uploaded image have a zero size

### ISSUE THREAD

**Issue by kareemzok** [SociallyDev/Spaces-API#62]
I updated the library to the new one. 
When I uploaded an image, I saw it on the space with zero size 

See attached image. What went wrong? it was working on old API 

I pass base64_decode() to the first param. I m not sure if its doable 

![image](https://user-images.githubusercontent.com/6444765/113755100-98976500-9718-11eb-92c9-b4544ac26a7e.png)

Please advice

**Comment by MacroMan** [comment]
Sorry it's taken so long to pick this up.

Do you still have the code around to replicate this issue?

**Comment by kareemzok** [comment]
Hello

Thanks for replying but the issue is resolved. 
We had problem assigining the mimetype but it works now.
