### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by gitleif** [SociallyDev/Spaces-API#64]
I get this errormessage when trying to upload file, using the code

`$space->uploadFile("G:\folder\file.jpg", $Path . "g54djDex1g/oa4cjefp8lq.jpg" , "public");`

Caught exception: Error executing "PutObject" on "https://XXXXX.ams3.digitaloceanspaces.com/g54djDex1g/oa4cjefp8lq.jpg"; AWS HTTP error: Client error: `PUT https://XXXXX.ams3.digitaloceanspaces.com/g54djDex1g/oa4cjefp8lq.jpg` resulted in a `403 Forbidden` response: SignatureDoesNotMatchtx000000000000005d94790-006091 (truncated...) SignatureDoesNotMatch (client): - SignatureDoesNotMatchtx000000000000005d94790-006091a5ae-7a850c9-ams3c7a850c9-ams3c-ams3-zg03

No mather what I do the error keep comming. The Spaces-API (version 1) worked without any problem.

**Comment by teebuphilip** [comment]
@gitleif - did you ever find a resolution - I am having the same issue?
my case is super wierd in that i have the code in 2 places, one side works and the other side gives me this error.
i even regenerated keys as well ?

**Comment by MacroMan** [comment]
I haven't been able to replicate this issue.

Can you provide more information, such as PHP version, full log output, a copy of the file being uploaded, and a full copy of the relavent code?
