### ISSUE TITLE
List directories only functionality

### ISSUE THREAD

**Issue by schmidtl4** [SociallyDev/Spaces-API#66]
What's the best way to get a listing only of folders.  I know that folders aren't really folders but prefixes to the file name.  That said, I'd like to be able to see just the folder names for a particular space.  Any way to do that?

**Comment by SociallyDev** [comment]
Hey,
There are a couple ways that I can think of to sort of achieve folder-like functionality:

- You could store folders in a separate database at the time of upload & refer to that database when you want folders.

- You can iterate over all objects, explode() the ones containing a `/` using the char `/`, and then join n - 1 parts back to form a folder & sub-folder structure.

**Comment by schmidtl4** [comment]
OK thanks - not exactly what I'd hoped for but thanks for the suggestions.
Les

  Les Schmidt
Simplicity, Clarity, Focus
Founder & Executive Director
BRIIA <https://briia.io/>
WE ACCELERATE INNOVATION

Why the Tri-Valley? See this
<http://www.bayareaeconomy.org/report/tri-valley-rising-2018/>!
LinkedIn BRIIA <https://www.linkedin.com/company/briia.io/> | Twitter BRIIA
<https://twitter.com/briia_io> | Medium ***@***.***_IO>
| LinkedIn
Les <https://www.linkedin.com/in/lesschmidt> | +1 408.242.4986

**Comment by MacroMan** [comment]
This could be a nice enhancement actually.

I'm reopening this a feature request

**Comment by divyeshJoshiG** [comment]
Please tell how to create a new folder in space, please tell api with example. Thanks

**Comment by MacroMan** [comment]
> Please tell how to create a new folder in space, please tell api with example. Thanks

You can't do that directly. Spaces doesn't support having an empty folder/directory.
You can upload text/file with the path, which will "create" the directory on demand:
`$space->uploadText('Lorem ipsum', 'folder-name/remote-filename.txt');`
If all files are removed, the folder/directory will be removed too.

**Comment by MacroMan** [comment]
This library is now deprecated and this feature will not be implemented. We recommend using the [official SDK](https://github.com/DigitalOceanPHP/Client) or the [Laravel package](https://github.com/GrahamCampbell/Laravel-DigitalOcean)
