### ISSUE TITLE
Space do not exist

### ISSUE THREAD

**Issue by PhamMinhKha** [SociallyDev/Spaces-API#69]
### What happened?

How to connect space. I get error with space do not exist
` 
ini_set('display_errors', 1);
        $accessKey = "KRFF3CFROMLHWJxxxx";
        $secretKey = "aajUBtoXwMDa2w2ObWiGmi7VULxKzDFYBEXTxxxxx";
        $spaceName = "images";
        $region = "sgp1";
        // Connect to a space
        $spaces = new Spaces($accessKey, $secretKey);
        $space = $spaces->space($spaceName, $region);
        print_r($space);
        exit();
`

### Version

2.0.1

### What version of PHP are you using?

7.3.27

### Relevant log output

```shell
An uncaught Exception was encountered
Type: SpacesAPI\Exceptions\SpaceDoesntExistException

Message: Space 'images' does not exist

Filename: /var/www/html/vendor/sociallydev/spaces-api/SpacesAPI/Space.php

Line Number: 49

Backtrace:

File: /var/www/html/vendor/sociallydev/spaces-api/SpacesAPI/Spaces.php
Line: 103
Function: __construct
```

**Comment by PhamMinhKha** [comment]
i use this config and working 
// Connect to a space
        $spaces = new Spaces($accessKey, $secretKey, $region);

**Comment by MacroMan** [comment]
Please generate new access keys. You have posted yours publicly in this bug.
