### ISSUE TITLE
[Question] Would you prefer simpler functions?

### ISSUE THREAD

**Issue by SociallyDev** [SociallyDev/Spaces-API#7]
**I'm writing a newer version of this wrapper and I have an idea**, making functions simpler using a sort-of representational execution.

Idea:
`$space->File("hello.text")` would return the actual file contents.
`$space->File("hello.text")->Metadata()` would return the metadata (eg creation date).
`$space->File("hello.text")->MakePublic()` would make a file public.
<br></br>

I'm not entirely sure if this exact example is feasible since it'd fetch the file first for even a completely unrelated action, but that's an issue for another day.
<br></br>

## Would you prefer simpler functions?

[![](https://api.gh-polls.com/poll/01CFAJ52MZHSMDA55P0K5AHG8V/Hell%20yeah!)](https://api.gh-polls.com/poll/01CFAJ52MZHSMDA55P0K5AHG8V/Hell%20yeah!/vote)
[![](https://api.gh-polls.com/poll/01CFAJ52MZHSMDA55P0K5AHG8V/No%2C%20normal%20functions%20are%20better)](https://api.gh-polls.com/poll/01CFAJ52MZHSMDA55P0K5AHG8V/No%2C%20normal%20functions%20are%20better/vote)

**Comment by AndreyNazarchuk** [comment]
What about 
```php
$space->File("hello.text")->Body()
```

or 

```php
$space->File("hello.text")->Save()
```

to get contents?

**Comment by SociallyDev** [comment]
@AndreyNazarchuk that's the plan right now.
Thinking about something even easier though.

<br />

To get contents:
```php
$space->Files("hello.text")->Get()
```

**Comment by SociallyDev** [comment]
Started working on simpler functions!
