### ISSUE TITLE
[Feature]: Rename/move

### ISSUE THREAD

**Issue by didyouexpectthat** [SociallyDev/Spaces-API#73]
### Description

Is it possible to implement rename/move files? I am trying to clean up the CDN which has improperly cased files, but DO is very slow. I seem to get awesome response using this API and hoping I can use it to rename the files.

Thank you.

**Comment by MacroMan** [comment]
I think that is a good idea. I will implement that in the next round of development

**Comment by MacroMan** [comment]
I have released v3.4.0 which includes a file move method. Use it like so:
`$fle->move('new-filename.txt');`

**Comment by schmidtl4** [comment]
@MacroMan 
Hurray for this addition!
1) I I assume the new method is meant to be: `$file->move... //with an "i"`
2) is it also safe to assume that the full implementation might be:
`$file('source path/file')->('new path/file');` ?

**Comment by MacroMan** [comment]
`$file` is just a reference to a `File` instance. It's currently documented in the API docs: https://github.com/SociallyDev/Spaces-API/blob/master/docs/File.md#filemove

You can use it like so:
```
$spaces = new Spaces('api-key', 'api-secret');
$space = $spaces->space('space-name');

$file = $space->file('test.txt');
$file->move('new-filename.txt');
```

I'll add an example to the readme

**Comment by schmidtl4** [comment]
Perfect.  Thank you.
The single line implementation - `$space->file($source)->move($dest);` works as well.  :)
