### ISSUE TITLE
[Feature]: Get CDN edge file URL

### ISSUE THREAD

**Issue by juhchamp** [SociallyDev/Spaces-API#76]
### Description

Hi, when using CDN to serve content I noticed that there is no option to retrieve url from cdn edge, could you implement this?
Currently getURL() returns the origin URL of the image, and I would like to retrieve the URL of the cdn edge, for example:
`<spacename>.<region>.cdn.digitaloceanspaces.com` instead of `<spacename>.<region>.digitaloceanspaces.com`

**Comment by MacroMan** [comment]
I'm not sure on the feasibility of this, but I will look into it and put this in the backlog if it's possible.

**Comment by MacroMan** [comment]
This library is now deprecated and this feature will not be implemented. We recommend using the [official SDK](https://github.com/DigitalOceanPHP/Client) or the [Laravel package](https://github.com/GrahamCampbell/Laravel-DigitalOcean)
