### ISSUE TITLE
What should the relative file path be for delete()?

### ISSUE THREAD

**Issue by kohle** [SociallyDev/Spaces-API#79]
### What happened?

I'm attempting to delete a file, but keep getting a FileDoesntExistException. This is the line of code:

`$space->file('/user/profile/' . $existing_image . '.png')->delete();`

`$existing_image` represents the file name without an extension.

I have verified that the file path I am entering does work when going to it directly in the browser. I've tried a few different combinations:
- Listing out the full URL of the Space ([name].nyc3.digitaloceanspaces.com)
- Using my CDN subdomain
- Prefixing the directory with a `/` or not
- Using my Space name at the start and not (/[name]/path/to/file)

What should I be using as a file path?

### Version

3.5.0

### Relevant log output

```shell
Fatal error: Uncaught SpacesAPI\Exceptions\FileDoesntExistException: File /user/profile/723beb107c171cce56f6c2e80a8ceb3d.png doesn't exist in /workspace/vendor/sociallydev/spaces-api/SpacesAPI/File.php:66 Stack trace: #0 /workspace/vendor/sociallydev/spaces-api/SpacesAPI/Space.php(334)
```
![image](https://user-images.githubusercontent.com/892288/174506912-3db8ee51-f35e-44ef-a910-1f498922b538.png)

**Comment by MacroMan** [comment]
Try listing the files out using `$space->listFiles('user/profile/')` and comparing that to your generated filename (`/user/profile/723beb107c171cce56f6c2e80a8ceb3d.png`).
See https://github.com/SociallyDev/Spaces-API/blob/master/docs/Examples.md#listing-files

Prefixing with a slash or using your space name in the filename won't work and is invalid.

**Comment by kohle** [comment]
Thank you, not sure what was going on before I started from scratch and verified the path using listFiles(). Everything is working now!
