### ISSUE TITLE
[Feature]: Purge CDN

### ISSUE THREAD

**Issue by didyouexpectthat** [SociallyDev/Spaces-API#82]
### Description

Hello again.
It would be nice if I could purge the CDN. Sometimes, a file is made public after an attempt at the edge URL, which prevents the file from being accessible immediately after setting public. After purging the file, it should be immediately accessible (something I currently have to login and go to Spaces and find the file to purge until timeout). Thanks in advance for your consideration.

**Comment by MacroMan** [comment]
This library is now deprecated and this feature will not be implemented. We recommend using the [official SDK](https://github.com/DigitalOceanPHP/Client) or the [Laravel package](https://github.com/GrahamCampbell/Laravel-DigitalOcean)
