### ISSUE TITLE
Class 'Spacesupload\SpacesAPI\Spaces' not found[Bug]: 

### ISSUE THREAD

**Issue by shabbirhasan** [SociallyDev/Spaces-API#83]
### What happened?

A PHP Error was encountered
Severity: Error

Message: Class 'Spacesupload\SpacesAPI\Spaces' not found

Filename: controllers/Spacefileupload.php

Line Number: 14

Backtrace:

### Version

3.0.0

**Comment by shabbirhasan** [comment]
This is my folder name : Spacesupload move all code in this folder

**Comment by MacroMan** [comment]
Yes, but how are you importing `SpacesAPI\Spaces`?

**Comment by shabbirhasan** [comment]
Okay I move SpacesAPI\Spaces in back my folder

**Comment by shabbirhasan** [comment]
Class 'SpacesAPI\Spaces' not found in

Getting same error

**Comment by MacroMan** [comment]
Are you not using composer? This library is namespaced and intended to be used with composer, so I'm not able to offer any more support if you're including this manually

**Comment by shabbirhasan** [comment]
Okay
