### ISSUE TITLE
[Bug]: GetSigned URL Performance Issue compared to V2 of API

### ISSUE THREAD

**Issue by muhammedc** [SociallyDev/Spaces-API#84]
### What happened?

After migrating to v3.5.0 from v2, the getsignedURL function performance has degraded significantly compared to v2, when used in a loop and getting the url for a bunch of stored files.

Prior in v2, this would take about 2-5 seconds to obtain and generate signed urls for about 30 files... now after migrating to v3.5.0, it takes about 15-20 seconds to generate the same...

Any ideas or suggestions?

### Version

3.5.0

### What version of PHP are you using?

7.4.1

**Comment by MacroMan** [comment]
We made changes to way file data is fetched from Spaces, and I know why it's taking you longer. I don't have a solution right now, but I will look into supporting what you need.

**Comment by muhammedc** [comment]
Many thanks for letting me know. Is there a temporary hack to speedup performance, or should I revert to v2 until such time a solution or fix is available?

**Comment by MacroMan** [comment]
Can you post the code loop you're using?

**Comment by MacroMan** [comment]
How are you retrieving `$filesResult`? If you used `$my_space->listFiles()` then you shouldn't need to do `$my_Space->file($f1['FILENAME'])->getsignedURL("15 minutes"))` but just `$f1->->getsignedURL("15 minutes"))`

**Comment by MacroMan** [comment]
I have just pushed an update. Upgrade to 3.6.0 and you can now pass a second arg to `Space::file(string $filename, bool $validate)` like so: `$my_Space->file($f1['FILENAME'], false)` which will disable checking if the file exists. This should speed up the call. Let me know if that has worked for you

**Comment by muhammedc** [comment]
> How are you retrieving `$filesResult`? If you used `$my_space->listFiles()` then you shouldn't need to do `$my_Space->file($f1['FILENAME'])->getsignedURL("15 minutes"))` but just `$f1->getsignedURL("15 minutes"))`

Hi - $fileResults - Thats an internal db query to get the list.

**Comment by muhammedc** [comment]
> I have just pushed an update. Upgrade to 3.6.0 and you can now pass a second arg to `Space::file(string $filename, bool $validate)` like so: `$my_Space->file($f1['FILENAME'], false)` which will disable checking if the file exists. This should speed up the call. Let me know if that has worked for you

Thanks - I will check and revert as soon as I am back from leave :-)

**Comment by MacroMan** [comment]
Have you had a chance to see if this has fixed your problem?

**Comment by muhammedc** [comment]
Hi, Not yet - Its scheduled for next weeks build test. Although I am gonna
try to schedule some time before - Will let you know ASAP. Sorry for the
delay - We are approaching build freeze and am running around trying to
tick off each TO DO Item before freeze.

**Comment by muhammedc** [comment]
I have tested it - There is a definite improvement - but still slow compared to v2.0.1.
Current benchmarks with 28 urls:
- v2.0.1 = 1 second
- v3.6.0 = 4 seconds

**Comment by MacroMan** [comment]
This library is now deprecated and this bug will not be fixed. We recommend using the [official SDK](https://github.com/DigitalOceanPHP/Client) or the [Laravel package](https://github.com/GrahamCampbell/Laravel-DigitalOcean)
