### ISSUE TITLE
[Bug]: This only works with region us-east-1 ?

### ISSUE THREAD

**Issue by alexbudin** [SociallyDev/Spaces-API#85]
### What happened?

You can clearly see from your Spaces class that the region is hardcoded to us-east-1, even though you allow for region the constructor, you actually use it for the endpoint URL and not the actual region S3 client instantiation.

Am i missing something ? Because i cannot get it to work with any region except spaces/buckets created in the us-east-1

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/832030/202037247-cc4e237c-1cd4-44f2-9e6d-81f8505b4bb2.png">

### Version

3.5.0

**Comment by MacroMan** [comment]
Hi, thanks for reporting. Pretty embarrassing that I missed this. Feel free to open a PR

**Comment by didyouexpectthat** [comment]
@alexbudin 
Can you tell me more about why you say `us-east-1` but the screenshot says `ams3` in the screenshot and the code? 

The part of the constructor you're looking at is setting the region to a default value when one isn't provided when calling a new `Spaces`. The examples assume you are using ams3. You can specify the region like below for my example of `spacename.sfo2.digitaloceanspaces.com`...

```
$DO_SPACES_KEY = "ABCDEFGHIJKLMNOPQRSTUVWYX";
$DO_SPACES_SECRET = "abcdefghjjklmnopqrstuvwxyzabcdefghijklmnop";
$DO_SPACES_REGION = "sfo2";
$spaces = new Spaces($DO_SPACES_KEY, $DO_SPACES_SECRET, $DO_SPACES_REGION);
$space = $spaces->space('spacename');
$files = $space->listFiles();
```

This is working amazingly for me. There's nothing wrong with the code from my usage.  The only time I can reproduce your same error is when I change the name of a space to one that does not exist. 


```
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught SpacesAPI\\Exceptions\\SpaceDoesntExistException: Space 'spacename' does not exist in /var/www/vendor/sociallydev/spaces-api/SpacesAPI/Space.php:49\n
Stack trace:\n
#0 /var/www/vendor/sociallydev/spaces-api/SpacesAPI/Spaces.php(103): SpacesAPI\\Space->__construct()\n
#1 /var/www/space_test.php(11): SpacesAPI\\Spaces->space()\n
#2 {main}\n  thrown in /var/www/vendor/sociallydev/spaces-api/SpacesAPI/Space.php on line 49'
```
The API key you generate from DigitalOcean has access to all the spaces with absolute paths like /spacename/path/to/stuff.  So, if you are the space `assets-storage.sfo2.digitaloceanspaces.com`, then you would change `$space = $spaces->space('spacename');` to `$space = $spaces->space('assets-storage');`

I hope this helps you.
