### ISSUE TITLE
[Feature]: Purge file from CDN cache

### ISSUE THREAD

**Issue by juhchamp** [SociallyDev/Spaces-API#86]
### Description

Would it be possible to add an option, similar to the one that exists in the options of each file "Purge from CDN cache" (see image), to remove the cache of a specific file from the CDN?
![image](https://user-images.githubusercontent.com/44661803/230746375-9c27b4f8-d1c4-4d8c-8358-896f0de09af6.png)

**Comment by jordan26** [comment]
+1 if possible

**Comment by MacroMan** [comment]
This library is now deprecated and this feature will not be implemented. We recommend using the [official SDK](https://github.com/DigitalOceanPHP/Client) or the [Laravel package](https://github.com/GrahamCampbell/Laravel-DigitalOcean)
